# These are the Rules. It tells NGINX: "Only talk to people using HTTPS (Port 443), 
# only use secure TLS protocols, and if someone asks for a website, send the 
# request to the WordPress container"

server {
    # Listen only on port 443 for SSL
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name mgodawat.42.fr;

    # SSL Certificate paths
    ssl_certificate /etc/nginx/ssl/mgodawat.crt;
    ssl_certificate_key /etc/nginx/ssl/mgodawat.key;

    # Mandatory: Only TLS 1.2 and 1.3 are allowed
    ssl_protocols TLSv1.2 TLSv1.3;

    root /var/www/html;
    index index.php index.html;

    server_name_in_redirect off;
    port_in_redirect off;    

    location / {
        try_files $uri $uri/ =404;
    }

    # Pass PHP scripts to the WordPress container on port 9000
    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass wordpress:9000;
	fastcgi_param HTTPS on;
    }
}
