services:
  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    restart: always
    env_file:
      - .env
    volumes:
      - /home/mgodawat/data/mariadb:/var/lib/mysql
    networks:
      - inception_net

  wordpress:
    depends_on:
      - mariadb
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    restart: always
    env_file:
      - .env
    volumes:
      - /home/mgodawat/data/wordpress:/var/www/html
    networks:
      - inception_net

  nginx:
    depends_on:
      - wordpress
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    restart: always
    ports:
      - "443:443"
    networks:
      - inception_net
    volumes:
      - /home/mgodawat/data/wordpress:/var/www/html

networks:
  inception_net:
    name: inception_net
    driver: bridge
